from django.urls import path
from core import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('webapps/', views.webapps_list, name='webapps_list'),
    path('webapps/add/', views.add_webapp_manual, name='add_webapp_manual'),
    path('targets/add/', views.target_add, name='target_add'),
    path('targets/<int:pk>/', views.target_detail, name='target_detail'),
    path('targets/<int:pk>/delete/', views.target_delete, name='target_delete'),
    path('scan/recon/', views.scan_recon, name='scan_recon'),
    path('task-status/<str:task_id>/', views.check_task_status, name='check_task_status'),
    path('targets/<int:pk>/edit/', views.target_edit, name='target_edit'),
    path('api/targets/<int:pk>/subdomains/', views.api_target_subdomains, name='api_subdomains'),
    path('api/targets/<int:pk>/webapps/', views.api_target_webapps, name='api_webapps'),
    path('scan/webapp/', views.scan_webapp, name='scan_webapp'),
    path('webapps/<int:pk>/', views.webapp_detail, name='webapp_detail'),
    path('webapps/<int:pk>/endpoints/', views.webapp_detail, name='webapp_endpoints'),
    path('webapps/<int:pk>/js-files/', views.webapp_js_files, name='webapp_js_files'),
    path('webapps/<int:pk>/archives/', views.webapp_archives, name='webapp_archives'),
    path('webapps/<int:pk>/client-routes/', views.webapp_client_routes, name='webapp_client_routes'),
    path('webapps/<int:pk>/delete/', views.webapp_delete, name='webapp_delete'),
    path('webapps/<int:pk>/js/', views.view_js_file, name='view_js_file'),
    path('webapps/<int:pk>/js-viewer/', views.js_viewer, name='js_viewer'),
    path('webapps/<int:pk>/js-summary/', views.js_summary, name='js_summary'),
    path('webapps/<int:pk>/js-summary/status/', views.js_summary_status, name='js_summary_status'),
    path('webapps/<int:pk>/js-routes/', views.js_routes, name='js_routes'),
    path('webapps/<int:pk>/js-routes/status/', views.js_routes_status, name='js_routes_status'),
    path('webapps/<int:pk>/js-code-review/', views.js_code_review, name='js_code_review'),
    path('webapps/<int:pk>/js-code-review/status/', views.js_code_review_status, name='js_code_review_status'),
    path('webapps/<int:pk>/js-analysis/cancel/', views.js_analysis_cancel, name='js_analysis_cancel'),
    path('task-cancel/<str:task_id>/', views.cancel_task, name='cancel_task'),
    path('api/targets/<int:pk>/vulnerabilities/', views.api_target_vulnerabilities, name='api_target_vulnerabilities'),
    path('api/webapps/<int:pk>/toggle-tested/', views.api_webapp_toggle_tested, name='api_webapp_toggle_tested'),
    path('api/targets/<int:pk>/add-subdomain/', views.api_add_subdomain, name='api_add_subdomain'),
    path('api/targets/<int:pk>/add-webapp/', views.api_add_webapp, name='api_add_webapp'),
    path('scan/vuln/', views.scan_vuln, name='scan_vuln'),
    path('vulnerabilities/<int:pk>/report/', views.vuln_report, name='vuln_report'),
    path('terminal/', views.terminal_view, name='terminal'),
    ]