services:
  automator:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: automator-backend
    ports:
     - "8000:8000"
    volumes:
      - .:/work
      - automator-history:/root
    environment:
      - PYTHONUNBUFFERED=1
      - PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/work/backend/core/bins:/usr/local/go/bin:/go/bin
      - TERM=xterm-256color
    working_dir: /work
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: redis
    env_file:
      - .env

  celery:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: celery
    command: celery -A websploit worker -l INFO
    volumes:
      - .:/work
      - automator-history:/root
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/work/backend
      - TERM=xterm-256color
      - PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/work/backend/core/bins:/usr/local/go/bin:/go/bin
    working_dir: /work
    depends_on:
      - redis
      - automator
    env_file:
      - .env

volumes:
  automator-history:
