# Generated by Django 4.2.11 on 2025-12-09 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=1000, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='Subdomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_alive', models.BooleanField(default=False)),
                ('hostname', models.CharField(max_length=1000)),
                ('cname', models.CharField(blank=True, max_length=1000, null=True)),
                ('ip', models.CharField(blank=True, max_length=1000, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdomains', to='core.domain')),
            ],
            options={
                'unique_together': {('domain', 'hostname')},
            },
        ),
        migrations.CreateModel(
            name='HTTPX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=1000000, null=True)),
                ('content_length', models.IntegerField(blank=True, null=True)),
                ('tech', models.JSONField(blank=True, default=list, null=True)),
                ('location', models.CharField(blank=True, max_length=1000000, null=True)),
                ('title', models.CharField(blank=True, max_length=1000000, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_fingerprint', to='core.domain')),
                ('subdomain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_fingerprint', to='core.subdomain')),
            ],
            options={
                'unique_together': {('subdomain', 'url')},
            },
        ),
    ]
