# Generated by Django 4.2.11 on 2025-12-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='httpx',
            name='domain',
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=10000, unique=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='hostname',
            field=models.CharField(max_length=10000, unique=True),
        ),
        migrations.AlterField(
            model_name='httpx',
            name='location',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='httpx',
            name='title',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='httpx',
            name='url',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='cname',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='hostname',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='ip',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
