# Generated by Django 4.2.11 on 2025-12-17 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_httpx_domain_alter_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubdomainTakeover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=1000, null=True)),
                ('severity', models.CharField(blank=True, max_length=1000, null=True)),
                ('target', models.JSONField(blank=True, default=list, null=True)),
                ('subdomain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdomain_takeover', to='core.subdomain')),
            ],
            options={
                'unique_together': {('subdomain', 'target')},
            },
        ),
    ]
