# Generated by Django 4.2.11 on 2025-12-17 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_subdomaintakeover'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subdomaintakeover',
            unique_together=set(),
        ),
    ]
