# Generated by Django 4.2.11 on 2026-05-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='webapplication',
            name='analyzed',
            field=models.BooleanField(default=False),
        ),
    ]
