# Generated by Django 4.2.11 on 2026-05-10 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_webapplication_analyzed'),
    ]

    operations = [
        migrations.CreateModel(
            name='JSFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('content', models.TextField(blank=True, null=True)),
                ('url', models.CharField(max_length=1000)),
                ('web_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='js_files', to='core.webapplication')),
            ],
            options={
                'unique_together': {('web_app', 'name')},
            },
        ),
    ]
