# Generated by Django 4.2.11 on 2026-05-11 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_jsfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSideRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2000)),
                ('web_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_side_routes', to='core.webapplication')),
            ],
            options={
                'unique_together': {('web_app', 'url')},
            },
        ),
    ]
