# Generated by Django 4.2.11 on 2026-05-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_clientsideroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsfile',
            name='usage_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
