# Generated by Django 4.2.11 on 2026-05-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_jsfile_usage_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsfile',
            name='routes_analysis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
