# Generated by Django 4.2.11 on 2026-05-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_jsfile_routes_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsfile',
            name='code_review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
