# Generated by Django 4.2.11 on 2026-06-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_jsfile_code_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='webapplication',
            name='tested',
            field=models.BooleanField(default=False),
        ),
    ]
