# Generated by Django 4.2.11 on 2026-06-21 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_vulnerability_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Port',
        ),
    ]
